### ISSUE TITLE
Navigation bar only translucent when using targetSdkVersion 29

### ISSUE THREAD

**Issue by yfunk** [crutchcorn/react-native-immersive-bars#3]
I tried to set this package up for my project, but ran into an issue where the navigation bar would not become fully transparent, but only translucent. I tested it on two emulators (API 29 and 30) and a Samsung phone (API 29).

To make sure that no other package was causing this I set up a brand new React Native project using the latest version of `react-native-community/react-native-template-typescript` (6.5.8). I added the following piece of code to the App component and changed the `minSdkVersion` to 21, since the project would not compile otherwise.
```
React.useEffect(() => {
    changeBarColors(false);
}, []);
```
The issue however did still occur.

<img width="720" alt="Screenshot_1606678553" src="https://user-images.githubusercontent.com/14955991/100553443-3a500680-328e-11eb-83c5-e48dbc7b3498.png">

Once I changed `targetSdkVersion` from `29` to `28` everything worked as intended.

I noticed a recent commit that seemed to relate to this and also that the package on npm doesn't seem to have been updated with it. So decided to install the package directly from GitHub using `npm i oceanbit-dev/react-native-immersive-bars#master --save`. This unfortunately did not seem to fix the issue.

**Dependencies in test project:**
```    
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-immersive-bars": "^1.0.1" (also "github:oceanbit-dev/react-native-immersive-bars#master")
```

**Comment by crutchcorn** [comment]
You've ran into the same unfortunate problem we have. It turns out that there is no way to have fully transparent navbars when toggling API 29. This seems to be a change made by Google themselves and, after a lot of research on our part, we have not found a workaround

**Comment by yfunk** [comment]
Damn, that's unfortunate. According to [this video](https://youtu.be/Nf-fP2u9vjI?t=62) about edge to edge apps it seems like they are drawing this translucent background "on lower end devices" for "background protection of navbar elements against the app", while one "higher end devices" the system looks at the content behind the navigation bar and decides if the controls need to be light or dark. Did you test this on a real device that could be considered high end to see if the navigation bar is fully transparent there?

**Comment by crutchcorn** [comment]
I've tested on both an S10+ and an LG V60 and have faced the same issue. I can't think of any other phone that would reasonably be considered "high-end"

**Comment by yfunk** [comment]
I would also consider these to be high-end devices, so if the system worked as explained in the video ~~the navigation bar should have been fully transparent on them.~~ [According to the docs](https://developer.android.com/training/gestures/gesturenav#transparent-bars) this behavior is only intended for the gesture navigation handle, which i was able to verify. When gesture navigation is activated in the device settings the navigation bar is fully transparent as intended.

However there is a glimpse of hope that there's a way to draw a fully transparent navigation bar for two and three button navigation. I was looking at some Apps made by Google when I noticed that YouTube also draws under the navigation bar (best visible when opening modals). If you slow down the animations you can clearly see the navigation bar being fully transparent on the same devices where there was a translucent background when using this package. I was able test this on Version 15.47.36 of the app (which targets API 30) and version 14.19.57 (which targets API 28), where both times the navigation bar was fully transparent.

They seem to be targeting API 29 from around version 14.31.50 to 15.34.36, but I could not get a version in this range to install properly as of yet. But considering the behavior of drawing a translucent background is intended for API 29 and up this working with a version of the YouTube app that targets API 30 would suggest it also works for one targeting API 29.

**Comment by yfunk** [comment]
@crutchcorn I found a solution. Adding `<item name="android:enforceNavigationBarContrast">false</item>` ([reference](https://developer.android.com/reference/android/R.attr#enforceNavigationBarContrast)) to `android\app\src\main\res\values\styles.xml` prevents the system from drawing the translucent background on targetSdk 29 and up. I tested it on API 29 and API 30 virtual devices, as well as on my API 29 Samsung device and haven't noticed any issues with it.

If there is a way to set this flag programmatically i think it should be added to the code, otherwise it should be mentioned in the README.

**Comment by crutchcorn** [comment]
No stinkin' way! I've looked for literal hours for such a flag and never found one! I'm pretty busy for the next day or two, but I'll try my best to investigate and code a solution.

Thank you so much for finding that, that actually helps our app a bunch!

**Comment by yfunk** [comment]
No problem, this package is helping me a lot with my app too so I guess we are kinda even ^^

If you update the repo please make sure to also update the package on npm, it seems like the latest commit from early August isn't on there yet.

**Comment by MoOx** [comment]
Would be nice to have this in the package :)

**Comment by crutchcorn** [comment]
Oh, you know what? I did the research on adding this to the package but never ended up commenting on the issue 😅. 

AFAIK, there is no way to add this style to the app programmatically. I've even asked two of my Android developer friends to no avail. As far as we can tell, the best way is to simply add:

```
<item name="android:enforceNavigationBarContrast">false</item>
```

To:

```
android\app\src\main\res\values\styles.xml
```

As explained by @yfunk. That said, we should update the README with this mention. I'll update the README with that change soon
