### ISSUE TITLE
code is always stubbed out, index.android.js never loaded

### ISSUE THREAD

**Issue by cleech** [crutchcorn/react-native-immersive-bars#6]
Commit d39449919aedeadcba78ce3ec3174474aa70b28f is incorrect, I think you need to just reference 'index' to get the platform specific extensions checked.  Currently metro is looking for 'index.js.android.js' and then picks up 'index.js' instead of 'index.android.js'

**Comment by crutchcorn** [comment]
Oh! See I thought I was "fixing" things but turns out I was breaking them all along 🙃 LOL I'll make a PR sometime this week

**Comment by crutchcorn** [comment]
`v1.0.4` has been published with this fix mentioned.

Thanks for reporting!
