### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by quicksnap** [crutchcorn/react-native-immersive-bars#7]
Works like a charm. Awesome job!

**Comment by crutchcorn** [comment]
Thank you kindly for the support :) 

Let me know if there's anything I can do to help integrate, add features or whatnot. While a distinct entity from OceanBit, I also run a programming Discord where we do pair programming calls and other programming chat - that's probably where would be best to reach me (even if it's unrelated to the library - happy to help with any development stuff):

https://discord.gg/FMcvc6T
